total_transactions = 10000
connection_threads = 4
connections = 20
duration = 50
ethereum_rpc_url = "http://127.0.0.1:8545"
rpc_url = "http://127.0.0.1:3000"
request_timeout = 15
chain_id = 1001
rollup_id = "radius_rollup"
signing_keys = [
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
]
# signing_keys = [
#     "0x79034809c2b4bd3c77a0ef831d4136c4779f1d1e4fe4b0c5b104a0e5a75a5a41",
#     "0xbf7e9ae142fbac146ba384f3252cece53a3dcf433ae0f4d7cdeb3e1c367b9474",
#     "0xaddbf6c59ada292328e2228b5d57115945d0bda0d7133e63bf622cbfb9f11478",
#     "0x2698b2ceeb7d535901833a494a18282718140ae5cad49095460f8e7fdbd1ead7",
#     "0x8d3d6bf510e92ba5c879d5296a7aa750fee08582e539eda6af1e252ebb7e7b9e",
#     "0x05bdacebf64abc8c5e3dbeeeedc5f73379431065ebef1d6d5e1cb7709851238e",
#     "0x7da9f971781819a6f82063f981d0e9cba6a5ef45b3a8b773c9a4aca3db3ef548",
#     "0x926ca8592baa8b961839627f83fcf9317d77ae8c149e6105b80bcd275f8eed6a",
#     "0xa250102f6a154cdad1fada79eeb83c83f00524d91d5699e1ac11a25d3be292ae",
#     "0x7118fbca78a2d79ab1d0b061b6939b006975765561c6390322283ad47d1b667e",
#     "0x08d0ef9dcb0524f4bd3ab64f5c929029ab883fdc8f83f9985d9022aad9584f16",
#     "0x6b1c5a8a833dbf5a78afba7c124a48d9b26eee85021ad66f6635d59ec963292e",
#     "0x00b91bc483ffee5c977655f10b99719b469e88522cd658b48426507e27f1bac1",
#     "0x5af773cf6665167a36e95a04b40cd85a325922a945d47bc73be5634b0e8a2cb2",
#     "0x14f97d75e2424e88ee625716d8634545bb833240c5bfbd8e5098fe495479c526",
#     "0x3bdfd3fc32d13701fd5494c68e71e6d80eb8bcf977b2ced8b840a05b66da8a30",
#     "0xf24b1617c9bd09d7b9a3f3d473fc321598904ae33ba5437c1b25ac702ece734f",
#     "0xf78b7c01a16c15c3b3eb429c157b2a8cadb9c7b67a81585574e2078fa39f17de",
#     "0x486d6b44645a939f90c7e01e11ee2fecf15b5f2acdc086466f14fa1f39585492",
#     "0x89a3616009514b4e621f437ca307a2a45bcf56b2dd7bc5d2d7e1c5e085a66d23",
#     "0xe20ef15f2ab21c11413f888e46dcd4336b42ea1bd040e4bf8e7fd4a590336226",
#     "0x154b91bb48367f8fae3eb266b62f7f4b7e9afa94cbaed26f3cc4b4debde6b162",
#     "0x14f7569df0af4f7c2adcd3820c09a43c52fe749b64a768ac86a47b9241f86449",
#     "0xa70364ea77a7a6c7c61863c350d434f2e1ec619888cbb28700b9849333ec1c77",
#     "0xcfd8527c937683df21ab7ba8c67c033a76315e9aadbaf399ab99416276bce6b9",
#     "0x560e466a41ea00f787bc15bb503e6845cc81481800f093c905254d9fee708831",
#     "0x3f06b870153d32767adaca8b4024731333b32493313cc3d663e963874c036d82",
#     "0xc887743243f4e92fcd9bdc819552b858ee9962759e24c70f15b88a02edf7fdfe",
#     "0xc241632d52ae23ec30cc488bb248c122c2f38c5dec869ea2d6d1d7e7f57191b7",
#     "0x811bbcd6295913e28963ac811b5bb4794ab1ab2d50baf66bc81eab800ae24380",
# ]